version: "3.9"
services:
#  database:
#    restart: always
#    image: postgres:14.1
  daemon:
    build:
      context: .
      args:
        RL_PROJECT_NAME: radiologger-daemon
        RL_EXECUTABLE_NAME: radiologgerd
  api:
    build:
      context: .
      args:
        RL_PROJECT_NAME: radiologger-api
        RL_EXECUTABLE_NAME: radiologger-api
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8000
      - ROCKET_PROFILE=production
    networks:
      - frontend
      - backend

  gui:
    build: ./radiologger-gui
    networks:
      - frontend

  nginx:
    build: ./nginx
    networks:
      - frontend
    ports:
      - 8000:80

networks:
  frontend:
  backend:
