[package]
name = "radiologger-daemon"
version = "6.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "radiologgerd"
path = "src/main.rs"

[dependencies]
radiologger-core = { path = "../radiologger-core" }
